# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html
AWSTemplateFormatVersion: '2010-09-09' 
Transform: AWS::Serverless-2016-10-31
Description: >
  A simple severless functions to read/write to DynamoDB

Globals:
  Function:
    Timeout: 5 # Please use 3-5 seconds for prod. 10s will cost more if there is any error.

Resources:
  GetFeedbackMsgDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: get-feedback-msg
      Handler: get-feedback-msg.lambdaHandler
      Runtime: nodejs12.x
      Description: GET all items from DynamoDB
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FeedbackMsgTable
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref FeedbackMsgTable
      
  PostFeedbackMsgDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post-feedback-msg.lambdaHandler
      Runtime: nodejs12.x
      Description: Post feedback msg to DynamoDB
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref FeedbackMsgTable
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref FeedbackMsgTable
      Events:
        PostFeedbackMsg:
          Type: Api
          Properties:
            Path: /feedback
            Method: post
            RestApiId:
              Ref: FeedbackApiGateway
            RequestModel:
              Model: FeedbackMsg
              Required: true

  FeedbackMsgTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  FeedbackApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Models:
        FeedbackMsg:
          type: object
          required:
            - msg
          properties:
            msg:
              type: string
